- name: create autossh user
  become: true
  when:
    - autossh_user_onlykey == false
    - autossh_offline_conf == false
  user:
    name: "{{autossh_user}}"
    system: yes
    append: yes
    shell: /bin/false
    generate_ssh_key: yes
    ssh_key_type: ED25519
    ssh_key_file: ".ssh/id_{{autossh_keyname}}"
    ssh_key_comment: "{{autossh_user}}@{{inventory_hostname}}"
- name: generate autossh key
  become: true
  when:
    - autossh_user_onlykey == true
    - autossh_offline_conf == false
  user:
    name: "{{autossh_user}}"
    generate_ssh_key: yes
    ssh_key_type: ED25519
    ssh_key_file: ".ssh/id_{{autossh_keyname}}"
    ssh_key_comment: "{{autossh_user}}@{{inventory_hostname}}"
- name: generate autossh key offline
  become: true
  when: autossh_offline_conf == true
  user:
    name: "{{ansible_user_id}}"
    generate_ssh_key: yes
    ssh_key_type: ED25519
    ssh_key_file: "{{autossh_path_prefix}}/home/{{autossh_user}}/.ssh/id_{{autossh_keyname}}"
    ssh_key_comment: "{{autossh_user}}@{{inventory_hostname}}"
- name: fetch public key
  fetch:
    src: "{{autossh_path_prefix}}/home/{{autossh_user}}/.ssh/id_{{autossh_keyname}}.pub"
    dest: "{{autossh_keyfetch_destination}}"
    flat: yes

- name: set .ssh/ owner recursively
  become: true
  when: autossh_offline_conf == true
  file:
    owner: 1000
    group: 1000
    recurse: yes
    path: "{{autossh_path_prefix}}/home/{{autossh_user}}/.ssh"

- name: prepare .ssh directory
  when: autossh_offline_conf == false
  become: true
  file:
    path: "{{autossh_path_prefix}}/home/{{autossh_user}}/.ssh"
    state: directory
    mode: 0755
    owner: "{{autossh_user}}"
- name: install autossh
  when: autossh_offline_conf == False
  become: true
  package:
    name: autossh
- name: deploy systemd unit for autossh tunnels
  tags: systemd
  become: true
  template:
    src: "{{autossh_unit_template}}"
    dest: "{{autossh_path_prefix}}/etc/systemd/system/{{autossh_unit_name}}.service"
  notify: restart autossh
- name: deploy ssh config to autossh user
  become: true
  when:
  - autossh_sshconfig_template_deploy == true
  - autossh_offline_conf == false
  template:
    src:  "{{autossh_sshconfig_template}}"
    dest: "{{autossh_path_prefix}}/home/{{autossh_user}}/.ssh/config"
    owner: "{{autossh_user}}"
  notify: restart autossh
- name: deploy ssh config to autossh user
  become: true
  when:
  - autossh_sshconfig_template_deploy == true
  - autossh_offline_conf == true
  template:
    src:  "{{autossh_sshconfig_template}}"
    dest: "{{autossh_path_prefix}}/home/{{autossh_user}}/.ssh/config"
    owner: 1000

- name: add known host
  known_hosts:
    name: "{{autossh_login_host}}"
    hash_host: yes
    key: "{{autossh_login_hostkey}}"
    path: "{{autossh_path_prefix}}/home/{{autossh_user}}/.ssh/known_hosts"
  notify: restart autossh

- name: Enable and start autossh tunnels
  when: autossh_offline_conf == False
  become: true
  systemd:
    name: "{{autossh_unit_name}}.service"
    enabled: true
    state: started
