- name: restart autossh
  when: autossh_onlineconf
  become: true
  systemd:
    name: "{{ autossh_unit_name }}.service"
    daemon_reload: true
    state: restarted
  async: 10
  poll: 0
  check_mode: no
